### ISSUE TITLE
Run Backend On My System

### ISSUE THREAD

**Issue by HamidRezaEbrahimi** [Glyphack/tortuga#58]
HI 
I try Run on Local but Dont Know About It Plz Add Doc For Easy Run .

**Comment by Glyphack** [comment]
Hi,
After installing requirements.txt you can use
```
uvicorn main:app
```
to run the app locally

**Comment by HamidRezaEbrahimi** [comment]
im try 
```sh
❯ pip install uvicorn
Out put
Requirement already satisfied: uvicorn in /home/hamidreza/.local/share/virtualenvs/tortuga-NNY1AdE1/lib/python3.8/site-packages (0.11.8)
Requirement already satisfied: h11<0.10,>=0.8 in /home/hamidreza/.local/share/virtualenvs/tortuga-NNY1AdE1/lib/python3.8/site-packages (from uvicorn) (0.9.0)
Requirement already satisfied: httptools==0.1.* in /home/hamidreza/.local/share/virtualenvs/tortuga-NNY1AdE1/lib/python3.8/site-packages (from uvicorn) (0.1.1)
Requirement already satisfied: click==7.* in /home/hamidreza/.local/share/virtualenvs/tortuga-NNY1AdE1/lib/python3.8/site-packages (from uvicorn) (7.1.2)
Requirement already satisfied: websockets==8.* in /home/hamidreza/.local/share/virtualenvs/tortuga-NNY1AdE1/lib/python3.8/site-packages (from uvicorn) (8.1)
Requirement already satisfied: uvloop>=0.14.0 in /home/hamidreza/.local/share/virtualenvs/tortuga-NNY1AdE1/lib/python3.8/site-packages (from uvicorn) (0.14.0)
```
 then :
```sh
uvicorn main:app

out put
Traceback (most recent call last):
  File "/home/hamidreza/.local/share/virtualenvs/tortuga-NNY1AdE1/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/hamidreza/.local/share/virtualenvs/tortuga-NNY1AdE1/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/hamidreza/.local/share/virtualenvs/tortuga-NNY1AdE1/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/hamidreza/.local/share/virtualenvs/tortuga-NNY1AdE1/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hamidreza/.local/share/virtualenvs/tortuga-NNY1AdE1/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/hamidreza/.local/share/virtualenvs/tortuga-NNY1AdE1/lib/python3.8/site-packages/uvicorn/main.py", line 339, in main
    run(**kwargs)
  File "/home/hamidreza/.local/share/virtualenvs/tortuga-NNY1AdE1/lib/python3.8/site-packages/uvicorn/main.py", line 362, in run
    server.run()
  File "/home/hamidreza/.local/share/virtualenvs/tortuga-NNY1AdE1/lib/python3.8/site-packages/uvicorn/main.py", line 390, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/home/hamidreza/.local/share/virtualenvs/tortuga-NNY1AdE1/lib/python3.8/site-packages/uvicorn/main.py", line 397, in serve
    config.load()
  File "/home/hamidreza/.local/share/virtualenvs/tortuga-NNY1AdE1/lib/python3.8/site-packages/uvicorn/config.py", line 278, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/hamidreza/.local/share/virtualenvs/tortuga-NNY1AdE1/lib/python3.8/site-packages/uvicorn/importer.py", line 23, in import_from_string
    raise exc from None
  File "/home/hamidreza/.local/share/virtualenvs/tortuga-NNY1AdE1/lib/python3.8/site-packages/uvicorn/importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./main.py", line 6, in <module>
    from app.core import config
```

**Comment by Glyphack** [comment]
Oh this should be run outside of the app folder:
```
uvicorn app.main:app
```
